#
# Makefile for drivers/telephony
#

obj-$(CONFIG_PHONE) += phonedev.o
obj-$(CONFIG_PHONE_IXJ) += ixj.o
obj-$(CONFIG_PHONE_IXJ_PCMCIA) += ixj_pcmcia.o
obj-$(CONFIG_ARCH_FEROCEON_MV78XX0) += ../../arch/arm/plat-feroceon/mv_drivers_lsp/mv_phone/
obj-$(CONFIG_ARCH_FEROCEON_KW) += ../../arch/arm/plat-feroceon-kw/mv_drivers_lsp/mv_phone/
